name: Deploy to Skynet

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm install
      - run: rm -r .cache
      - run: rm -r dist
      - run: node_modules/.bin/parcel build index.html

      - name: "Deploy to Skynet"
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}
